### ISSUE TITLE
Issue in Add inventory schema

### ISSUE THREAD

**Issue by prathyu99** [prathyu99/CSC510_Group25_Project1#4]
add inventory schema needs to be fixed . 
Error: ADD_INVENTORY_HISTORY not found

**Comment by yuktasree** [comment]
Added inventory history schema reducer to combined reducers. 
Please refer to: https://github.com/prathyu99/CSC510_Group25_Project1/commit/d685e6d7d99268b57fa94a10e1415ab6cb568011
Issued fixed successfully
