### ISSUE TITLE
Notifications for expired items are not popping up for dates >=2023

### ISSUE THREAD

**Issue by SurajRKU** [prathyu99/CSC510_Group25_Project1#5]
Notifications for expired items are not popping up for dates >=2023

We need to fix the logic for popping expired notifications

**Comment by SurajRKU** [comment]
Refer commit #9ca722c9351ef496b562ec28e02066bb5b326225
Notifications were not popping up for dates >=2023 because the date verification in notifications had some mismatch in the logic. Fixed the logic and the issue has been resolved

**Comment by prathyu99** [comment]
Refer commit #9ca722c9351ef496b562ec28e02066bb5b326225
Notifications were not popping up for dates >=2023 because the date verification in notifications had some mismatch in the logic. Fixed the logic and the issue has been resolved
